# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Spyrous Blog
tagline:             'Digitally Inspired'
description:         'A blog about programming in the world of hardware'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Spyros Chiotakis
  url:               https://twitter.com/mdo
  email:             spyros.chiotakis@gmail.com

highlighter: rouge
markdown:    kramdown

# Gems
gems: [jekyll-paginate]