# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Spyros Chiotakis Blog
tagline:             ''
description:         'A blog about programming in the world of hardware'
url:                 #http://lanyon.getpoole.com
paginate:            10
highlighter:         null
paginate_path: "page:num"

# About/contact
author:
  name:              Spyros Chiotakis
  url:               www.spyroschiotakis.com
  email:             spyros.chiotakis@gmail.com

highlighter: rouge
markdown:    kramdown

permalink: /:categories/:title/

# Gems
gems: [jekyll-paginate]